annotations:
  created: "2025-10-21T10:47:05Z"
  revision: 0301b627cb80d52e5a2942e53a247c8437f02add
apiVersion: v2
appVersion: 3.1.2-3
description: Deploy the MX Grid Manager app-orch pod
name: orch-ui-app-orch
type: application
version: 3.1.2-3
