annotations:
  created: "2025-10-14T07:06:01Z"
  revision: 625fddb684be1d83285ce3763c6591615a9df795
apiVersion: v2
appVersion: 3.1.2-2
description: Deploy the MX Grid Manager cluster-orch pod
name: orch-ui-cluster-orch
type: application
version: 3.1.2-2
