annotations:
  created: "2025-10-14T07:08:43Z"
  revision: 625fddb684be1d83285ce3763c6591615a9df795
apiVersion: v2
appVersion: 3.1.2-2
description: Deploy MX Grid Manager UI pods on Kubernetes
name: orch-ui-root
type: application
version: 3.1.2-2
